### ISSUE TITLE
.env missing from tests folder

### ISSUE THREAD

**Issue by doylelew** [elestio-examples/attendize#1]
the readme in the tests folder instructs the user to copy the .env from the tests folder into the root, but there is no .env to copy in the repository

**Comment by AmsellemJoseph** [comment]
Hey @doylelew 

You were right, the env file is now in the tests folder, don't forget to do the commands in the following order:

    ./scripts/preInstall.sh
    docker-compose up -d
    ./scripts/postInstall.sh

Have a nice day 😊
